-- MySQL Script generated by MySQL Workbench
-- 07/13/16 19:47:26
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bookcase
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bookcase
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bookcase` DEFAULT CHARACTER SET utf8mb4 ;
USE `bookcase` ;

-- -----------------------------------------------------
-- Table `bookcase`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookcase`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(40) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookcase`.`books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookcase`.`books` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `author` VARCHAR(50) NOT NULL,
  `price` DOUBLE NOT NULL,
  `user` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `books_users_idx` (`user` ASC),
  CONSTRAINT `books_users`
    FOREIGN KEY (`user`)
    REFERENCES `bookcase`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookcase`.`chapters`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookcase`.`chapters` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  `pages` INT NOT NULL DEFAULT 1,
  `book` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `chapters_book_idx` (`book` ASC),
  CONSTRAINT `chapters_book`
    FOREIGN KEY (`book`)
    REFERENCES `bookcase`.`books` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
