<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitce5a7c4f56b78f95d174db98b8a7e491
{
    public static $prefixLengthsPsr4 = array (
        'R' => 
        array (
            'Respect\\Validation\\' => 19,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Respect\\Validation\\' => 
        array (
            0 => __DIR__ . '/..' . '/respect/validation/library',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitce5a7c4f56b78f95d174db98b8a7e491::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitce5a7c4f56b78f95d174db98b8a7e491::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
